name: drupal9
icon: drupal9
title: Drupal 9

services:
- name: php
  title: PHP
  service: drupal9-php
  required: true
  derivatives:
  - name: sshd
    service: drupal9-php-sshd
  options:
  - version: '8.1'
    default: true
  - version: '8.0'
  - version: '7.4'
  containers:
  - name: php
    env:
    - name: PHP_MEMORY_LIMIT
      value: 512M
    resources:
      request:
        cpu: 100
        memory: 16
  volumes:
  - name: files
    size: 50
  links:
  - name: db
    service: mariadb
  cron:
  - name: drush
    title: drush cron
    command: drush -r ${HTTP_ROOT} -l ${WODBY_URL_PRIMARY} cron
    schedule: 25 * * * *

- name: nginx
  title: Nginx
  service: drupal9-nginx
  required: true
  links:
  - name: backend
    service: php
  cron:
  - name: test
    title: test
    command: echo "123"
    schedule: 0 * * * *

- name: mariadb
  title: MariaDB
  service: mariadb
  volumes:
  - name: mysql-data
    size: 20

- name: cloud-mariadb
  title: Cloud MariaDB
  service: cloud-mariadb
  disabled: true
  options:
  - version: '10.3'

- name: cloud-mysql
  title: Cloud MySQL
  service: cloud-mysql
  disabled: true
  options:
  - version: '5.5'
  - version: '5.6'
  - version: '5.7'
  - version: '8'

tokens:
- name: random_token
  generate:
    regex: '[0-9a-z]{5,10}'
- name: db_backup_ignore_tables
  value: 'cache_%;cache;ctools_object_cache;ctools_views_cache;flood;history;queue;search_index;semaphore;sequences;sessions;watchdog'
