name: drupal8
title: Drupal 8

services:
- name: php
  title: PHP
  service: drupal8-php
  required: true
  options:
  - version: 7.4
  - version: 7.3
  derivatives:
  - name: sshd
    service: drupal8-php-sshd  
  containers:
  - name: php
    env:
    - name: PHP_MEMORY_LIMIT
      value: 512M
    resources:
      request:
        cpu: 100
        memory: 16
  volumes:
  - name: files
    size: 50
  links:
  - name: db
    service: mariadb

- name: nginx
  title: Nginx
  service: drupal8-nginx
  required: true
  links:
  - name: backend
    service: php

- name: mariadb
  title: MariaDB
  service: mariadb
  volumes:
  - name: mysql-data
    size: 20

- name: cloud-mariadb
  title: Cloud MariaDB
  disabled: true
  service: cloud-mariadb
  options: 
  - version: 10.3

#- name: newrelic
#  service: newrelic:0.1.0

env:
- name: ADD_THIS_ENV_TO_ALL_SVCS
  value: test
- name: RANDOM_ENV_VAR
  secret: true
  value: '{{random_token}}'

tokens:
- name: random_token
  generate:
    regex: '[0-9a-z]{5,10}'
- name: db_backup_ignore_tables
  value: 'cache_%;cache;ctools_object_cache;ctools_views_cache;flood;history;queue;search_index;semaphore;sequences;sessions;watchdog'
