name: drupal8
title: Drupal 8

services:
- name: php
  title: PHP
  service: drupal8-php
  required: true
  options:
  - 7.4
  - 7.3
  containers:
  - name: php
    env:
    - name: PHP_MEMORY_LIMIT
      value: 512M
    resources:
      request:
        cpu: 100
        memory: 16
  storage:
  - name: files
    size: 50
  links:
  - name: db
    service: mariadb

- name: nginx
  title: Nginx
  service: drupal8-nginx
  required: true
  links:
  - name: backend
    service: php

- name: mariadb
  title: MariaDB
  service: mariadb
  storage:
  - name: mysql-data
    size: 20

- name: cloud-mariadb
  title: Cloud MariaDB
  service: cloud-mariadb
  options: 
  - 10.3

#- name: newrelic
#  service: newrelic:0.1.0

env:
- name: ADD_THIS_ENV_TO_ALL_SVCS
  value: test
- name: RANDOM_ENV_VAR
  secret: true
  value: '{{random_token}}'

tokens:
- name: random_token
  generate:
  - regex: '[0-9a-z]{5,10}'
